### PR TITLE
Remember dark/light mode setting between reloads.

### LINKED ISSUE #205: Remember dark/light mode setting between reloads
**Description**

Dark/light mode preference is not remembered.

**To Reproduce**

1. Visit any page of `blog.px.dev`.
1. Page should load in light mode.
1. Click the theme button (sun or moon) in the top right corner.
1. Page switches to dark mode.
1. Refresh the page.
1. Page reverts to light mode, forgetting that the user asked for dark mode.

**Expected Behavior**

Upon reload, the last theme chosen by the user (dark or light) should be restored.
The page should default to light mode if the user hasn't explicitly selected dark mode, as it does today. It doesn't check the operating system or browser setting.

**Additional Context**

`src/components/mainThemeProvider.tsx` is the place to look.

### PR DESCRIPTION
**Pull request by NickLanam**
Clicking the theme selector now saves the preference in localStorage. This preference is remembered on page load. Since light mode is default, the item is removed when choosing light mode.

Fixes #205 

Signed-off-by: Nick Lanam <nlanam@pixielabs.ai>

### CODE REVIEW

File: src/components/mainThemeProvider.tsx [hunk 1]
```diff
@@ -18,23 +18,40 @@
...
 import * as React from 'react';
 import { ThemeProvider } from '@material-ui/styles';
-import { createMuiTheme } from '@material-ui/core';
+import { createMuiTheme, ThemeOptions } from '@material-ui/core';
 
 import AppThemeOptions from './theme';
 
+function setManualPreference(mode: 'light'|'dark') {
+  if (mode === 'light') {
+    localStorage.removeItem('theme');
```
Comment (vihangm) [inline src/components/mainThemeProvider.tsx:27]: should we just set `light` explicitly too? that way, if we change defaults, it still remembers the last thing someone used.

**Review by vihangm — CHANGES_REQUESTED** [review]
Looks like the netlify preview fails
```
11:18:11 AM: error "localStorage" is not available during server side rendering.
11:18:11 AM: 
11:18:11 AM: 
11:18:11 AM:   ReferenceError: localStorage is not defined
```

**Review by vihangm — APPROVED** [review]
